### PR TITLE
Example of using Full Text Search with TaylorSource & YapDatabaseExtensions

### PR DESCRIPTION
**Pull request by danthorpe**

### CODE REVIEW

**Comment by danthorpe** [comment]
A couple of things to highlight, because the FTS search is definitely a bit magical in YapDatabase. It works thanks to the coordination of a couple of components both of which are `YapDatabaseExtensions`s. There is a `YapDatabaseSearchResultsView` for the "search results", and there is a `YapDatabaseSearchQueue` which is where the search terms go.

In YapDatabaseExtensions, these components are wrapped up, in [`YapDB.SearchResults`](https://github.com/danthorpe/YapDatabaseExtensions/blob/development/YapDatabaseExtensions/Shared/YapDB.swift#L294) and [`YapDB.Search`](https://github.com/danthorpe/YapDatabaseExtensions/blob/development/YapDatabaseExtensions/Shared/YapDB.swift#L524) respectively.

The latter component is quite interesting. Although it can be used directly, it's easier to subclass it, and then provide the "query" internally. The query is a block which receives the search term from the user, and constructs a Full Text Search query string. Read the docs in YapDatabase for a link to how this string should be formatted. This Search object maintains it's own database connection and search queue. As the method `usingTerm(: String)` is called, it will enqueue a query onto its search queue and then perform the search (asynchronously) in the database on all of the result views. Oh that's right, you can use the same `Search` instance to update multiple search result views.

It is also relatively trivial to extend this class to support "remote search", as it's not too tricky to kick off a network request which could search your server using the search term, and write the results back into the database. This can effectively give you local caching of a remote server FTS.

There is some other interesting stuff going on here too.

We've defined a `CitiesDatasource` which is a `DatasourceProviderType` (from TaylorSource). It is basically responsible for driving the `UITableView` of the controller with all the items. It can also drive the `UITableView` of the search results too. We can achieve this with a simple `enum Kind { case All, SearchResults }` which we use to get a `TaylorSource.Configuration<City>` value. In turn, this is what encompasses the `YapDatabaseView` (of all the cities, or of the search results) and provides us with correct mapping to `City` types.

Other stuff: there is a nice example of how to load content from the app bundle into YapDatabase before loading the table view, although this could be improved with some sort of "Loading..." state in the view controller.

More other stuff: in `Domain.swift` there are some static properties which create `YapDB.Fetch` values, and then static functions which return `TaylorSource.Configuration` values. The difference between these things is a bit subtle, so I'll recap...
- `YapDB.Fetch`: an enum which wraps either a `View`, or `FilteredView` or `SearchResults`. It allows you to filter and sort items.
- `YapDB.FetchConfiguration`: is a struct which combines a `YapDB.Fetch` with `YapDB.Mappings` and a `MappingsConfigurationBlock?` these both allow control of modifying the groups in the fetch, either by filtering them out or sorting them.
- `TaylorSource.Configuration<T>` is a struct which combines a `YapDB.FetchConfiguration` with a `DataItemMapper` which is just a `AnyObject? -> T?` block. This is to support the use of value types in the models. If using ValueCoding, then supplying the `decode` static method of your type will work here.

So... putting this all together: to create the datasource for the search results, we get this configuration:

``` swift
extension City {

    static let searchResults: YapDB.Fetch = {

        let handler: YapDB.SearchResults.Handler = .ByObject({ dictionary, collection, key, object in
            if collection == City.collection, let city = City.decode(object) {
                dictionary.setObject(city.name, forKey: "name")
            }
        })

        let results = YapDB.SearchResults(name: "Cities by Name Search Results", parent: viewByState, search: CitySearch.name, columnNames: ["name"], handler: handler, collections: [collection])

        return .Search(results)
    }()

    static func searchResults(mappingBlock: YapDB.FetchConfiguration.MappingsConfigurationBlock? = .None) -> TaylorSource.Configuration<City> {
        let config = YapDB.FetchConfiguration(fetch: searchResults, block: mappingBlock)
        return TaylorSource.Configuration(fetch: config, itemMapper: City.decode)
    }
}
```

Okay... so what's all this stuff about a "handler" then? 

Well... the way the FTS module actually works, is that we have that query string, remember? This generally looks like this: `"key:searchTerm*"` and you can pretty much think of it as key, value search pairs. Now, when the `YapDatabaseSearchResultsViewExtension` is registered in the database, it gets fed all of the objects in the database. With each one it creates a dictionary of these key, value pairs. So, in our case we set the city name on a dictionary for the key "name". The trick here is that you don't really want to do anything computationally expensive - I think it's best just to populate the dictionary with the values for your search keys.

So, the last bit is then setting up the view controller. For this, I think it's best have an "abstract" view controller which can create or vend the necessary datasources - as you'll need two one for all the data, and one for the search results. I've actually done an app where we had a segmented control in the nav bar, with FTS search, so we had 4 datasources - works quite nicely.

In the top view controller, you'll then just need to set up the `UISearchController`, instantiating the search results view controller, and acting as the delegate for the `UISearchResultsUpdating`. This is where you'd execute new searches:

``` self
extension SearchableUSCitiesViewController: UISearchResultsUpdating {

    func updateSearchResultsForSearchController(searchController: UISearchController) {
        search.usingTerm(searchController.searchBar.text ?? "")
    }
}
```

In the above code, `search` is an instance of our `YapDB.Search` subclass.

Make sense?

**Comment by aranasaurus** [comment]
I'm just looking at this now and wanted to point out that this throws that exception on first launch that I reported as a crash with a collectionView.  The tableView implementation swallows the exception, but the tableView doesn't update until the app is restarted. So if you run this on a device or simulator that doesn't yet have the app on it, and disable the debugger (since the debugger will stop when the exception is thrown), you'll get an empty tableView, but you can search and that all works, but when viewing all, you get an empty table until you restart. 

I'm running into a similar problem in my app when large amounts of data are added or removed at once (log in/log out, for instance).

**Comment by aranasaurus** [comment]
Thanks a ton for the thorough explanation of how all of this works! I'm seeing that we were not doing some things in our implementation... but it's all on my co-worker's computer and he's out today, so I won't get to dive into actually comparing notes until (hopefully) tomorrow.

**Comment by danthorpe** [comment]
@aranasaurus okay, that's good to know about regarding the swelling of executions. Essentially, next release of TaylorSource is going to be a pretty significant overhaul, and this is one of the things on my hit-list:
- [ ] Swift 2.0 style API
- [ ] Proper view updating without swallowing exceptions.
- [ ] Support for `NSFetchedResultsController`

**Pull request merged**
